# Generated by Django 4.0.2 on 2022-04-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('book_writer', models.CharField(max_length=100)),
                ('booktype', models.CharField(max_length=100)),
                ('update_date', models.DateField()),
                ('price', models.IntegerField()),
                ('availabality', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'books',
            },
        ),
    ]
